### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by mciach**

### CODE REVIEW

**Comment by grzsko** [comment]
I know that somebody would say that I am blocking but I have several proposals to this tutorials apart from this PR:
- cell 4: change „downloadable at https://github.com/mciach/masserstein” to pip,
- cell 5: please add commented wget commands. I know that user can do this on her own, but tutorials are much nicer, and learning is smoother when everything works out of the box. I just uncomment cell, download files, ciach, ciach and everything done!
- cell 13: it would be clearer if the Z variable is set to 1,
- cell about 21: why do you do what you do by hand? It should not be part of masserstein.spectrum?,
- these cells: it is unclear why you plot TIC. What is the aim of this exercise?, All of these pictures are just black rectangle :-D
-  ok, when you reach the third picture, something happens.
- cell about 31: in_region is commented, so NameError is raised.
Enough for now. I reached to resampling.

**Comment by grzsko** [comment]
I do not know where is approve button :-O

**Review by michalsta — APPROVED** [review]
Yes, "someone" would say that you revieweing but not using the approve button, when repo is set in such a way that you can't merge without someone else's approval, is exactly the point.

Approving. Not merging yet though, those suggestions might be worth implementing, at Ciach's discretion.

**Comment by grzsko** [comment]
> Yes, "someone" would say that you revieweing but not using the approve button, when repo is set in such a way that you can't merge without someone else's approval, is exactly the point.
> 
> Approving. Not merging yet though, those suggestions might be worth implementing, at Ciach's discretion.

It is exactly what I want to do - approve and leave merging up to Ciach! But... where is an approve without merge button? When I was reviewing I had only approve and merge...

In general github is becoming more and more unclear and unintuitive (where is this button?!). But, when did these changes started? And who is the owner of github?

Microsoft! Please, do not destroy github like skype!

**Comment by michalsta** [comment]
IIRC, you have to click the "review" button, the one in the box which contains the (inactive) "merge pull request" button, and then you are taken to screen where you can approve, approve and comment, just comment, or request changes. Feel free to practice on PR #18 :P

**Review by grzsko — APPROVED** [review]

**Comment by grzsko** [comment]
> IIRC, you have to click the "review" button, the one in the box which contains the (inactive) "merge pull request" button, and then you are taken to screen where you can approve, approve and comment, just comment, or request changes. Feel free to practice on PR #18 :P

There is no "review" button, only "preview" :-D But I can click "Files changed", then "Review changes" and there is "Approve" and no "approve and merge". Probably you requested Ciach's review, not mine. But last time, in this PR there was a different set of buttons, strange.

**Pull request merged**
